:global:
  componentName: openshift4-config
  githubUrl: https://github.com/ZuGao/component-openshift4-config
  feature_goldenTests: true

docs/antora.yml:
  name: openshift4-config
  title: openshift4-config
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
