= Parameters

The parent key for all the following parameters is `openshift4_config`.

== `globalPullSecret`

[horizontal]
type:: string
default:: absent

[IMPORTANT]
====
This parameter is deprecated.
Please migrate your additional pull secrets to parameter `globalPullSecrets`.
====

A Vault reference pointing to the Vault secret containing the docker configuration file in JSON format.
If the parameter is null, the component doesn't manage the cluster's global pull secret.

The component writes the value of this parameter into the field `.dockerconfigjson` of the secret `pull-secret` in namespace `openshift-config`.

See the OpenShift documentation for more details on https://docs.openshift.com/container-platform/latest/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secret[managing the cluster's global pull secret].

[IMPORTANT]
====
You need to make sure that the existing pull secrets present on a cluster (deployed by the OpenShift installer) are included in the configuration deployed by this component.
Otherwise, OpenShift cluster services may stop working because their respective container images can't be downloaded anymore.
====

== `globalPullSecrets`

[horizontal]
type:: dict
default:: `{}`
example::
+
[source,yaml]
----
docker.io:
  email: dockerhub@example.com <1>
  auth: ?{vaultkv:${cluster:tenant}/${cluster:name}/openshift4-config/docker.io-pull-secret} <2>
----
<1> Some registries require an email address to be present for authenticated pulls.
<2> We strongly recommend that you store the `auth` value for the registry in Vault.

This parameter allows customizing the OpenShift cluster pull-secret without having to replicate the complete secret contents in Vault.
The component expects entries in the dict to be valid entries for the `.dockerconfigjson` `auths` field.
The component allows users to remove existing entries (also entries originally created by the OpenShift installer) by setting the value for a registry host to `null`.

[NOTE]
====
The component doesn't base64-encode the value provided for `auth`.
Please make sure that you store the `auth` value as base64 in Vault.
====

== `caBundle`

[horizontal]
type:: string
default:: `null`
example::
+
[source,yaml]
----
caBundle: | <1>
  -----BEGIN CERTIFICATE-----
  MY AWESOME CA
  -----END CERTIFICATE-----
----
<1> Custom CA deployed as ConfigMap `syn-ca-bundle`.

This parameter allows to deploy a ConfigMap in the `openshift-config` namespace.
The ConfigMap contains the configured CA in the key `ca-bundle.crt`, to be used by other components.

[IMPORTANT]
====
This ConfigMap isn't used by OpenShift components.
OpenShift uses a separate config map called `user-ca-bundle` in namespace `openshift-config` to extend the system wide trusted CA bundle.
See parameter `trustedCA` in component https://hub.syn.tools/openshift4-proxy/references/parameters.html#_trustedca[openshift4-proxy] for details on how to deploy additional trusted CA certificates for the system-wide trusted CA bundle.
====

== `cloud`

[horizontal]
type:: string
default:: `null`

The cloud provider on which the cluster is running.
Currently, the component only looks at this parameter to check whether to manage vSphere credentials, see also parameter <<_vsphere,`vsphere`>>.

== `vsphere`

[horizontal]
type:: dictionary
default:: `{"vcenterURL": null, "username": null, "password": null}`

The vSphere credentials for the cluster.

If parameter <<_cloud,`cloud`>> is `vsphere`, the component verifies that none of the fields are `null` and deploys a secret `appuio-vsphere-creds` in namespace `openshift-config`.
The contents of that secret are preformatted to work as contents for secret `vsphere-creds` in namespace `kube-system`.
The component needs the vCenter URL because the secret fields must be named `<vcenter-url>.username` and `<vcenter-url>.password`.
In addition to the secret the component also deploys an Espejote `ManagedResource` in namespace `openshift-config`.
The `ManagedResource` copies the contents of secret `appuio-vsphere-creds` to secret `vsphere-creds` in namespace `kube-system`.

TIP: We deploy a custom secret and a `ManagedResource` so that the vSphere credentials are not directly embedded into the `ManagedResource`'s `spec.template` on the cluster.

NOTE: If parameter `cloud` isn't set to `vsphere`, the contents of this parameter are ignored.

== `motd`

[horizontal]
type:: dictionary

Configure OpenShift's message of the day which is displayed in the terminal when using `oc login`.

=== `motd.messages`

[horizontal]
type:: dictionary
default:: `{}`

A dictionary of messages to be displayed in the message of the day.
Entries with `null` values are skipped.
This allows users to remove notifications which were configured higher up in the hierarchy.

=== `motd.include_console_notifications`

[horizontal]
type:: boolean
default:: `false`

Whether to include the console notifications from https://github.com/appuio/component-openshift4-console/blob/master/docs/modules/ROOT/pages/references/parameters.adoc#notifications[component-openshift4-console] in the message of the day.

The component will include each console notification's `spec.text` and `spec.link` contents in the following form:

[source,text]
----
<spec.text>
<spec.link.text>: <spec.link.href>
----

For console notifications which don't provide `spec.link`, the second line will be omitted.

== `etcdCustomziation`

[horizontal]
type:: dictionary

This parameter allows customizing the cluster's etcd.
The implementation uses https://github.com/vshn/espejote[Espejote] to reconcile our customizations for the `etcd.operator.openshift.io/cluster` resource.

=== `etcdCustomization.enabled`

[horizontal]
type:: boolean
default:: `false`

Whether to deploy the Espejote managed resource on the cluster.
If this parameter is set to `false`, changing the contents of `etcd.spec` has no effect.

=== `etcdCustomization.spec`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-openshift4-config/blob/master/class/defaults.yml[See `class/defaults.yml`]

A partial `spec` for the OpenShift 4 `Etcd` custom resource.
See the https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/operator_apis/etcd-operator-openshift-io-v1#spec-11[upstream API documentation] for available fields.


== `networkCustomization`

[horizontal]
type:: dictionary

This parameter allows customizing the cluster's networking.
The implementation uses https://github.com/vshn/espejote[Espejote] to reconcile our customizations for the `networks.config.openshift.io/cluster` and `networks.operator.openshift.io/cluster` resource.

=== `networkCustomization.enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy the Espejote managed resource on the cluster.
If this parameter is set to `false`, changing the contents of `networkCustomization` has no effect.

=== `networkCustomization.labelConfig` and `networkCustomization.labelOperator`

[horizontal]
type:: string
default::
+
[source,text]
----
labelConfig: 'network.openshift-config.syn.tools/include-config'
labelOperator: 'network.openshift-config.syn.tools/include-operator'
----

Other components can create configmaps in the `openshift-config` namespace with their own spec for the cluster resources.
If they label those configmaps with these keys, they get merged into the final configuration.

For more information, see xref:how-tos/networking-config.adoc[].

[IMPORTANT]
====
The ManagedResource collects all configmaps and sorts them by name before merging the specs into the configuration.
The config specified in this component will have precedence over any conflicting config in the configmaps.
====

=== `networkCustomization.specConfig` and `networkCustomization.specOperator`

[horizontal]
type:: string
default::
+
[source,text]
----
specConfig: {}
specOperator: {}
----

This are the specs for the resources `networks.config.openshift.io/cluster` and `networks.operator.openshift.io/cluster`.
