= Parameters

The parent key for all the following parameters is `openshift4_config`.

== `globalPullSecret`

[horizontal]
type:: string
default:: absent

[IMPORTANT]
====
This parameter is deprecated.
Please migrate your additional pull secrets to parameter `globalPullSecrets`.
====

A Vault reference pointing to the Vault secret containing the docker configuration file in JSON format.
If the parameter is null, the component doesn't manage the cluster's global pull secret.

The component writes the value of this parameter into the field `.dockerconfigjson` of the secret `pull-secret` in namespace `openshift-config`.

See the OpenShift documentation for more details on https://docs.openshift.com/container-platform/latest/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secret[managing the cluster's global pull secret].

[IMPORTANT]
====
You need to make sure that the existing pull secrets present on a cluster (deployed by the OpenShift installer) are included in the configuration deployed by this component.
Otherwise, OpenShift cluster services may stop working because their respective container images can't be downloaded anymore.
====

== `globalPullSecrets`

[horizontal]
type:: dict
default:: `{}`
example::
+
[source,yaml]
----
docker.io:
  email: dockerhub@example.com <1>
  auth: ?{vaultkv:${cluster:tenant}/${cluster:name}/openshift4-config/docker.io-pull-secret} <2>
----
<1> Some registries require an email address to be present for authenticated pulls.
<2> We strongly recommend that you store the `auth` value for the registry in Vault.

This parameter allows customizing the OpenShift cluster pull-secret without having to replicate the complete secret contents in Vault.
The component expects entries in the dict to be valid entries for the `.dockerconfigjson` `auths` field.
The component allows users to remove existing entries (also entries originally created by the OpenShift installer) by setting the value for a registry host to `null`.

[NOTE]
====
The component doesn't base64-encode the value provided for `auth`.
Please make sure that you store the `auth` value as base64 in Vault.
====

== `motd`

[horizontal]
type:: dictionary

Configure OpenShift's message of the day which is displayed in the terminal when using `oc login`.

=== `motd.messages`

[horizontal]
type:: dictionary
default:: `{}`

A dictionary of messages to be displayed in the message of the day.
Entries with `null` values are skipped.
This allows users to remove notifications which were configured higher up in the hierarchy.

=== `motd.include_console_notifications`

[horizontal]
type:: boolean
default:: `false`

Whether to include the console notifications from https://github.com/appuio/component-openshift4-console/blob/master/docs/modules/ROOT/pages/references/parameters.adoc#notifications[component-openshift4-console] in the message of the day.

The component will include each console notification's `spec.text` and `spec.link` contents in the following form:

[source,text]
----
<spec.text>
<spec.link.text>: <spec.link.href>
----

For console notifications which don't provide `spec.link`, the second line will be omitted.

== `etcd`

[horizontal]
type:: dictionary

This parameter allows configuring the cluster's etcd.
The implementation uses https://github.com/vshn/espejote[Espejote] to reconcile our customizations for the `etcd.operator.openshift.io/cluster` resource.

=== `etcd.enabled`

[horizontal]
type:: booloean
default:: `false`

Whether to deploy the Espejote managed resource on the cluster.
If this parameter is set to `false`, changing the contents of `etcd.spec` has no effect.

== `etcd.spec`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-openshift4-config/blob/master/class/defaults.yml[See `class/defaults.yml`]

A partial `spec` for the OpenShift 4 `Etcd` custom resource.
See the https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/operator_apis/etcd-operator-openshift-io-v1#spec-11[upstream API documentation] for available fields.
